[project]
name = "usda-plant-scraper"
version = "0.1.0"
description = "Asynchronous scraper and data pipeline for USDA PLANTS DATABASE"
authors = [{ name = "Tyler Nardone" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"

dependencies = ["httpx>=0.27", "pandas>=2.2", "tqdm>=4.66"]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.23",
    "ruff>=0.5",
    "black>=24.0",
    "mypy>=1.10",
]

[tool.ruff.lint]
extend-select = ["E", "C90", "C901", "I", "PD", "N", "B"]
ignore = ["PD901"]

[tool.ruff.lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 8
